### PR TITLE
Mobile direction focus icons

### PR DESCRIPTION
**Pull request by xem**
## Description
Add a return button and an indication icon when a mobile itinerary field is focused

## Why
To be able to know which field we are in, and to be able to return to the itinerary form easily

## Screenshots
image
image

### CODE REVIEW

**Comment by amatissart** [comment]
I wonder how difficult it would be to simplify these css changes using flexbox.  
What do you think @bbecquet ?

**Comment by bbecquet** [comment]
> I wonder how difficult it would be to simplify these css changes using flexbox.
> What do you think @bbecquet ?

It would be a less fragile layout and really easy to do with flexbox, but as things are done for now it would require a small change in the `<DirectionInput>` component to put a special class on the container div when the field is focused.

Right now this is the `<input>` element itself with is given a fixed, 100% width and top: 0 position, which is why we are forced to use these complex ~ selectors everywhere and use absolute positioning for all the siblings.
IMO it reflects more closely how things work if the parent container, not the input, gets a special display state. We would have code easier to read and maintain. Do you think it's worth the JS change?

**Note: I just discovered it's theoretically doable with CSS only with the new `:focus-within` pseudo-class https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within, but we may have support issue on some browsers**

**Comment by bbecquet** [comment]
Switching to flexbox would also simplify the desktop layout, as for now it uses absolute positioning too for the icon and cross.

**Comment by xem** [comment]
In general, I prefer using CSS (even if it involves sibling selectors, which I don't find very complex) than JS when it's possible.

In this case, indeed, the field and its neighbours have custom look and behavior on PC and mobile...
I'd rather keep the CSS solution, but if you prefer that I flag the parent container when the field is focused, it's ok for me too.

**Comment by xem** [comment]
sure!

**Pull request merged**
