### PR TITLE
QMAPS: reenable right click

### PR DESCRIPTION
**Pull request by xem**
## Description
enable right click on the panels container

## Why
it's weird

### CODE REVIEW

**Comment by amatissart** [comment]
This was introduced by https://github.com/QwantResearch/erdapfel/commit/d123a1dea35787b0c8e67d568c446c046e88b920
So maybe @GuillaumeGomez would have more context to explain this change ?

**Comment by GuillaumeGomez** [comment]
The event was transmissed to the map and was ugly to use. Don't see why it's weird or whatever as is but it's very likely that the bug will reappear now...

**Comment by amatissart** [comment]
It seems weird that it would be propagated to the map. Do you remember how to reproduce the bug exactly ?

**Comment by GuillaumeGomez** [comment]
Not sure... We found it out while looking for something else but I \*think\* that it's by right-clicking on the panel directly (not on any button).

**Pull request merged**
